// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4AgrX3YQUdmW2UgwvhLONql902P12z20',
    appId: '1:224479132873:web:9a4c1289c8a1dcd87f6118',
    messagingSenderId: '224479132873',
    projectId: 'e-wallet-backend',
    authDomain: 'e-wallet-backend.firebaseapp.com',
    storageBucket: 'e-wallet-backend.appspot.com',
    measurementId: 'G-MP1BY9D7TL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGGD8DDr090aY4_PtOIwC9UcVVP698Au0',
    appId: '1:224479132873:android:6e2daa0d29fc10857f6118',
    messagingSenderId: '224479132873',
    projectId: 'e-wallet-backend',
    storageBucket: 'e-wallet-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr8B5zCJUizjRf3sZ35MihhQJlNGbPK5U',
    appId: '1:224479132873:ios:b5bacbf35b5a9a6c7f6118',
    messagingSenderId: '224479132873',
    projectId: 'e-wallet-backend',
    storageBucket: 'e-wallet-backend.appspot.com',
    iosClientId: '224479132873-8tdr08lft3dq1ujssqbp258rarprautp.apps.googleusercontent.com',
    iosBundleId: 'com.example.ewalletApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr8B5zCJUizjRf3sZ35MihhQJlNGbPK5U',
    appId: '1:224479132873:ios:b5bacbf35b5a9a6c7f6118',
    messagingSenderId: '224479132873',
    projectId: 'e-wallet-backend',
    storageBucket: 'e-wallet-backend.appspot.com',
    iosClientId: '224479132873-8tdr08lft3dq1ujssqbp258rarprautp.apps.googleusercontent.com',
    iosBundleId: 'com.example.ewalletApp',
  );
}
